---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: veryfreshpod-rbac
  labels:
    app: veryfreshpod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: veryfreshpod-rbac
  labels:
    app: veryfreshpod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: veryfreshpod-rbac
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: veryfreshpod-config
  namespace: kube-system
  labels:
    app: veryfreshpod
data:
  VFP_DEBUG: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veryfreshpod
  namespace: kube-system
  labels:
    app: veryfreshpod
spec:
  selector:
    matchLabels:
      app: veryfreshpod
  template:
    metadata:
      labels:
        app: veryfreshpod
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: veryfreshpod
          image: test:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: veryfreshpod-config
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
